server:
  port : 14567
    servlet :
    	contextPath : /api/v1
spring:
  datasource:
    username : test
    password : 
    url : jdbc:mysql://localhost:3306/test?useSSL=false
    hostname : localhost
